CC=gcc
CFLAGS=-I.

all:parallel_min_max process_memory.o utils.o find_min_max.o 
parallel_min_max : utils.o find_min_max.o utils.h find_min_max.h
	$(CC) -o parallel_min_max utils.o find_min_max.o parallel_min_max.c $(CFLAGS)

utils.o : utils.h
	$(CC) -o utils.o -c utils.c $(CFLAGS)

find_min_max.o : utils.h find_min_max.h
	$(CC) -o find_min_max.o -c find_min_max.c $(CFLAGS)

process_memory.o: 
	$(CC) -c process_memory.c $(CFLAGS)
	$(CC) process_memory.o -o process_memory $(CFLAGS)

clean :
	rm utils.o find_min_max.o  parallel_min_max process_memory

